//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AuditoriaPrivilegios.java
//  @ Date : 29/04/2015
//  @ Author : 
//
//



package com.yanbal.lib.corp.auditoria;

/**
 * Implementación de la auditoria de privilegios
 * @author jcabrera
 * @author ovalencia
 * @version 1.0 Abril 2015
 */
public interface AuditoriaPrivilegios {
}
