SET SCHEMA KSK_KIOSKO
/
 
INSERT INTO KSK_PAIS(NOMBRE,CODIGO_PAIS) 
VALUES('Peru','PER')
/
INSERT INTO KSK_PAIS(NOMBRE,CODIGO_PAIS) 
VALUES('Colombia','P002')
/
INSERT INTO KSK_PAIS(NOMBRE,CODIGO_PAIS) 
VALUES('Venezuela','P003')
/
INSERT INTO KSK_PAIS(NOMBRE,CODIGO_PAIS) 
VALUES('Chile','P004')
/
INSERT INTO KSK_PAIS(NOMBRE,CODIGO_PAIS) 
VALUES('Ecuador','P005')
/



INSERT INTO KSK_ROL(NOMBRE,CODIGO_ROL) 
VALUES('Directora','A001')
/
INSERT INTO KSK_ROL(NOMBRE,CODIGO_ROL) 
VALUES('Consultora','A002')
/
INSERT INTO KSK_ROL(NOMBRE,CODIGO_ROL) 
VALUES('Estrella','A003')
/
INSERT INTO KSK_ROL(NOMBRE,CODIGO_ROL) 
VALUES('Staff','A004')
/
INSERT INTO KSK_ROL(NOMBRE,CODIGO_ROL) 
VALUES('Aspirante','A005')
/


INSERT INTO KSK_COLECCION(
CORRELATIVO_COLECCION_PADRE, NOMBRE, NIVEL, USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(NULL,'Coleccion 01', 1, 'SISTEMA', (SELECT current timestamp FROM sysibm.sysdummy1))
/
INSERT INTO KSK_COLECCION(
CORRELATIVO_COLECCION_PADRE, NOMBRE, NIVEL, USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(NULL,'Coleccion 02', 1, 'SISTEMA', (SELECT current timestamp FROM sysibm.sysdummy1))
/
INSERT INTO KSK_COLECCION(
CORRELATIVO_COLECCION_PADRE, NOMBRE, NIVEL, USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(NULL,'Coleccion 03', 1, 'SISTEMA', (SELECT current timestamp FROM sysibm.sysdummy1))
/


INSERT INTO KSK_COLECCION(
CORRELATIVO_COLECCION_PADRE, NOMBRE, NIVEL, USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(1,'Coleccion 0101', 2, 'SISTEMA', (SELECT current timestamp FROM sysibm.sysdummy1))
/
INSERT INTO KSK_COLECCION(
CORRELATIVO_COLECCION_PADRE, NOMBRE, NIVEL, USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(1,'Coleccion 0102', 2, 'SISTEMA', (SELECT current timestamp FROM sysibm.sysdummy1))
/
INSERT INTO KSK_COLECCION(
CORRELATIVO_COLECCION_PADRE, NOMBRE, NIVEL, USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(1,'Coleccion 0103', 2, 'SISTEMA', (SELECT current timestamp FROM sysibm.sysdummy1))
/
INSERT INTO KSK_COLECCION(
CORRELATIVO_COLECCION_PADRE, NOMBRE, NIVEL, USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(1,'Coleccion 0104', 2, 'SISTEMA', (SELECT current timestamp FROM sysibm.sysdummy1))
/

INSERT INTO KSK_COLECCION(
CORRELATIVO_COLECCION_PADRE, NOMBRE, NIVEL, USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(2,'Coleccion 0201', 2, 'SISTEMA', (SELECT current timestamp FROM sysibm.sysdummy1))
/

INSERT INTO KSK_COLECCION(
CORRELATIVO_COLECCION_PADRE, NOMBRE, NIVEL, USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(3,'Coleccion 0301', 2, 'SISTEMA', (SELECT current timestamp FROM sysibm.sysdummy1))
/
INSERT INTO KSK_COLECCION(
CORRELATIVO_COLECCION_PADRE, NOMBRE, NIVEL, USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(3,'Coleccion 0302', 2, 'SISTEMA', (SELECT current timestamp FROM sysibm.sysdummy1))
/
INSERT INTO KSK_COLECCION(
CORRELATIVO_COLECCION_PADRE, NOMBRE, NIVEL, USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(3,'Coleccion 0303', 2, 'SISTEMA', (SELECT current timestamp FROM sysibm.sysdummy1))
/


INSERT INTO KSK_COLECCION(
CORRELATIVO_COLECCION_PADRE, NOMBRE, NIVEL, USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(4,'Coleccion 010101', 3, 'SISTEMA', (SELECT current timestamp FROM sysibm.sysdummy1))
/
INSERT INTO KSK_COLECCION(
CORRELATIVO_COLECCION_PADRE, NOMBRE, NIVEL, USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(5,'Coleccion 010201', 3, 'SISTEMA', (SELECT current timestamp FROM sysibm.sysdummy1))
/
INSERT INTO KSK_COLECCION(
CORRELATIVO_COLECCION_PADRE, NOMBRE, NIVEL, USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(6,'Coleccion 010301', 3, 'SISTEMA', (SELECT current timestamp FROM sysibm.sysdummy1))
/
INSERT INTO KSK_COLECCION(
CORRELATIVO_COLECCION_PADRE, NOMBRE, NIVEL, USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(7,'Coleccion 010401', 3, 'SISTEMA', (SELECT current timestamp FROM sysibm.sysdummy1))
/



INSERT INTO KSK_KIOSKO.KSK_FORMATO_ARCHIVO(EXTENSION,DESCRIPCION,DESCARGA,CARGA,USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES('PDF','Joint Photographic Experts Group JFIF format',20,50,'SISTEMA',(SELECT current timestamp FROM sysibm.sysdummy1))
/
INSERT INTO KSK_KIOSKO.KSK_FORMATO_ARCHIVO(EXTENSION,DESCRIPCION,DESCARGA,CARGA,USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES('MP4','MPEG-4 Video Stream',20,50,'SISTEMA',(SELECT current timestamp FROM sysibm.sysdummy1))
/
INSERT INTO KSK_KIOSKO.KSK_FORMATO_ARCHIVO(EXTENSION,DESCRIPCION,DESCARGA,CARGA,USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES('MP3','MPEG Layer 3 Audio',10,15,'SISTEMA',(SELECT current timestamp FROM sysibm.sysdummy1))
/
INSERT INTO KSK_KIOSKO.KSK_FORMATO_ARCHIVO(EXTENSION,DESCRIPCION,DESCARGA,CARGA,USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES('JPG','Joint Photographic Experts Group JFIF format',20,50,'SISTEMA',(SELECT current timestamp FROM sysibm.sysdummy1))
/





INSERT INTO KSK_KIOSKO.KSK_ARCHIVO(
CORRELATIVO_COLECCION, CORRELATIVO_PAIS,CORRELATIVO_ROL,NOMBRE, 
DESCRIPCION,TAMANHO, EXTENSION, NRO_ORDEN, DESCARGABLE,DESTACADO,
RUTA_ARCHIVO,RUTA_IMGPREVIA,
FECHA_INICIO,FECHA_CADUCIDAD,FECHA_SINCRONIZACION,
ELIMINADO,USUARIO_REGISTRA)
VALUES(
1,1,1,'Archivo 01',
'Archivo de prueba 0001 desc', '10.0', 'JPG', 1, 1, 1,
'http://img-9gag-fun.9cache.com/photo/avLgyyb_700b_v2.jpg', 'http://img-9gag-fun.9cache.com/photo/aOmVxGy_700b.jpg', 
(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),
0,'SISTEMA'
)
/

INSERT INTO KSK_KIOSKO.KSK_ARCHIVO(
CORRELATIVO_COLECCION, CORRELATIVO_PAIS,CORRELATIVO_ROL,NOMBRE, 
DESCRIPCION,TAMANHO, EXTENSION, NRO_ORDEN, DESCARGABLE,DESTACADO,
RUTA_ARCHIVO,RUTA_IMGPREVIA,
FECHA_INICIO,FECHA_CADUCIDAD,FECHA_SINCRONIZACION,
ELIMINADO,USUARIO_REGISTRA)
VALUES(
1,1,1,'Archivo 02',
'Archivo de prueba 0002 desc', '10.0', 'PDF', 2, 1, 1,
'http://www.urartuuniversity.com/content_images/pdf-sample.pdf', 'http://img-9gag-fun.9cache.com/photo/aOmVxGy_700b.jpg', 
(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),
0,'SISTEMA'
)
/



INSERT INTO KSK_KIOSKO.KSK_ARCHIVO(
CORRELATIVO_COLECCION, CORRELATIVO_PAIS,CORRELATIVO_ROL,NOMBRE, 
DESCRIPCION,TAMANHO, EXTENSION, NRO_ORDEN, DESCARGABLE,DESTACADO,
RUTA_ARCHIVO,RUTA_IMGPREVIA,
FECHA_INICIO,FECHA_CADUCIDAD,FECHA_SINCRONIZACION,
ELIMINADO,USUARIO_REGISTRA)
VALUES(
1,1,1,'Archivo 03',
'Archivo de prueba 0003 desc', '10.0', 'MP4', 3, 1, 1,
'http://sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4', 'http://img-9gag-fun.9cache.com/photo/aOmVxGy_700b.jpg', 
(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),
0,'SISTEMA'
)
/


INSERT INTO KSK_KIOSKO.KSK_ARCHIVO(
CORRELATIVO_COLECCION, CORRELATIVO_PAIS,CORRELATIVO_ROL,NOMBRE, 
DESCRIPCION,TAMANHO, EXTENSION, NRO_ORDEN, DESCARGABLE,DESTACADO,
RUTA_ARCHIVO,RUTA_IMGPREVIA,
FECHA_INICIO,FECHA_CADUCIDAD,FECHA_SINCRONIZACION,
ELIMINADO,USUARIO_REGISTRA)
VALUES(
2,1,1,'Archivo 04',
'Archivo de prueba 0004 desc', '10.0', 'MP3', 1, 1, 1,
'http://www.noiseaddicts.com/samples_1w72b820/2232.mp3', 'http://img-9gag-fun.9cache.com/photo/aOmVxGy_700b.jpg', 
(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),
0,'SISTEMA'
)
/

INSERT INTO KSK_KIOSKO.KSK_ARCHIVO(
CORRELATIVO_COLECCION, CORRELATIVO_PAIS,CORRELATIVO_ROL,NOMBRE, 
DESCRIPCION,TAMANHO, EXTENSION, NRO_ORDEN, DESCARGABLE,DESTACADO,
RUTA_ARCHIVO,RUTA_IMGPREVIA,
FECHA_INICIO,FECHA_CADUCIDAD,FECHA_SINCRONIZACION,
ELIMINADO,USUARIO_REGISTRA)
VALUES(
2,1,1,'Archivo 05',
'Archivo de prueba 0005 desc', '10.0', 'JPG', 2, 1, 1,
'http://img-9gag-fun.9cache.com/photo/avLgyyb_700b_v2.jpg', 'http://img-9gag-fun.9cache.com/photo/aOmVxGy_700b.jpg', 
(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),
0,'SISTEMA'
)
/

INSERT INTO KSK_KIOSKO.KSK_ARCHIVO(
CORRELATIVO_COLECCION, CORRELATIVO_PAIS,CORRELATIVO_ROL,NOMBRE, 
DESCRIPCION,TAMANHO, EXTENSION, NRO_ORDEN, DESCARGABLE,DESTACADO,
RUTA_ARCHIVO,RUTA_IMGPREVIA,
FECHA_INICIO,FECHA_CADUCIDAD,FECHA_SINCRONIZACION,
ELIMINADO,USUARIO_REGISTRA)
VALUES(
2,1,1,'Archivo 06',
'Archivo de prueba 0006 desc', '10.0', 'PDF', 3, 1, 1,
'http://www.urartuuniversity.com/content_images/pdf-sample.pdf', 'http://img-9gag-fun.9cache.com/photo/aOmVxGy_700b.jpg', 
(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),
0,'SISTEMA'
)
/


INSERT INTO KSK_KIOSKO.KSK_ARCHIVO(
CORRELATIVO_COLECCION, CORRELATIVO_PAIS,CORRELATIVO_ROL,NOMBRE, 
DESCRIPCION,TAMANHO, EXTENSION, NRO_ORDEN, DESCARGABLE,DESTACADO,
RUTA_ARCHIVO,RUTA_IMGPREVIA,
FECHA_INICIO,FECHA_CADUCIDAD,FECHA_SINCRONIZACION,
ELIMINADO,USUARIO_REGISTRA)
VALUES(
10,1,1,'Archivo 07',
'Archivo de prueba 0007 desc', '10.0', 'MP4', 3, 1, 1,
'http://sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4', 'http://img-9gag-fun.9cache.com/photo/aOmVxGy_700b.jpg', 
(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),
0,'SISTEMA'
)
/

INSERT INTO KSK_KIOSKO.KSK_ARCHIVO(
CORRELATIVO_COLECCION, CORRELATIVO_PAIS,CORRELATIVO_ROL,NOMBRE, 
DESCRIPCION,TAMANHO, EXTENSION, NRO_ORDEN, DESCARGABLE,DESTACADO,
RUTA_ARCHIVO,RUTA_IMGPREVIA,
FECHA_INICIO,FECHA_CADUCIDAD,FECHA_SINCRONIZACION,
ELIMINADO,USUARIO_REGISTRA)
VALUES(
10,1,1,'Archivo 08',
'Archivo de prueba 0008 desc', '10.0', 'MP3', 1, 1, 1,
'http://www.noiseaddicts.com/samples_1w72b820/2232.mp3','http://img-9gag-fun.9cache.com/photo/aOmVxGy_700b.jpg', 
(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),(SELECT current timestamp FROM sysibm.sysdummy1),
0,'SISTEMA'
)
/


INSERT INTO  KSK_PARAMETRO(NOMBRE_PARAMETRO, VALOR_PARAMETRO)
VALUES('FechaUltimaActualizacionPais','2015-07-02')
/

INSERT INTO  KSK_PARAMETRO(NOMBRE_PARAMETRO, VALOR_PARAMETRO)
VALUES('HorasExpiracionToken','24')

/

UPDATE KSK_COLECCION
SET
NRO_ORDEN = 1,
DESCRIPCION = 'La Coleccion 01'
WHERE CORRELATIVO_COLECCION = 1 
/

UPDATE KSK_COLECCION
SET
NRO_ORDEN = 2,
DESCRIPCION = 'La Coleccion 02'
WHERE CORRELATIVO_COLECCION = 2
/ 

UPDATE KSK_COLECCION
SET
NRO_ORDEN = 3,
DESCRIPCION = 'La Coleccion 03'
WHERE CORRELATIVO_COLECCION = 3
/ 


COMMIT
/


UPDATE KSK_COLECCION
SET
NRO_ORDEN = 1,
DESCRIPCION = 'La Coleccion 0101'
WHERE CORRELATIVO_COLECCION = 4
/ 
UPDATE KSK_COLECCION
SET
NRO_ORDEN = 2,
DESCRIPCION = 'La Coleccion 0102'
WHERE CORRELATIVO_COLECCION = 5
/ 
UPDATE KSK_COLECCION
SET
NRO_ORDEN = 3,
DESCRIPCION = 'La Coleccion 0103'
WHERE CORRELATIVO_COLECCION = 6
/ 
UPDATE KSK_COLECCION
SET
NRO_ORDEN = 4,
DESCRIPCION = 'La Coleccion 0104'
WHERE CORRELATIVO_COLECCION = 7
/


UPDATE KSK_COLECCION
SET
NRO_ORDEN = 1,
DESCRIPCION = 'La Coleccion 0201'
WHERE CORRELATIVO_COLECCION = 8
/

UPDATE KSK_COLECCION
SET
NRO_ORDEN = 1,
DESCRIPCION = 'La Coleccion 0301'
WHERE CORRELATIVO_COLECCION = 9
/
UPDATE KSK_COLECCION
SET
NRO_ORDEN = 2,
DESCRIPCION = 'La Coleccion 0302'
WHERE CORRELATIVO_COLECCION = 10
/
UPDATE KSK_COLECCION
SET
NRO_ORDEN = 3,
DESCRIPCION = 'La Coleccion 0303'
WHERE CORRELATIVO_COLECCION = 11
/

UPDATE KSK_COLECCION
SET
NRO_ORDEN = 1,
DESCRIPCION = 'La Coleccion 010101'
WHERE CORRELATIVO_COLECCION = 12
/

UPDATE KSK_COLECCION
SET
NRO_ORDEN = 1,
DESCRIPCION = 'La Coleccion 010201'
WHERE CORRELATIVO_COLECCION = 13
/
UPDATE KSK_COLECCION
SET
NRO_ORDEN = 1,
DESCRIPCION = 'La Coleccion 010301'
WHERE CORRELATIVO_COLECCION = 14
/
UPDATE KSK_COLECCION
SET
NRO_ORDEN = 1,
DESCRIPCION = 'La Coleccion 010401'
WHERE CORRELATIVO_COLECCION = 15
/

COMMIT
/
