INSERT INTO KSK_KIOSKO.KSK_FORMATO_ARCHIVO(EXTENSION,DESCRIPCION,DESCARGA,CARGA,USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES('.pdf','Joint Photographic Experts Group JFIF format',2,5,'SISTEMA',(SELECT current date FROM sysibm.sysdummy1))
/
INSERT INTO KSK_KIOSKO.KSK_FORMATO_ARCHIVO(EXTENSION,DESCRIPCION,DESCARGA,CARGA,USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES('.mp4','MPEG-4 Video Stream',20,50,'SISTEMA',(SELECT current date FROM sysibm.sysdummy1))
/
INSERT INTO KSK_KIOSKO.KSK_FORMATO_ARCHIVO(EXTENSION,DESCRIPCION,DESCARGA,CARGA,USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES('.mp3','MPEG Layer 3 Audio',10,15,'SISTEMA',(SELECT current date FROM sysibm.sysdummy1))
/
INSERT INTO KSK_KIOSKO.KSK_FORMATO_ARCHIVO(EXTENSION,DESCRIPCION,DESCARGA,CARGA,USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES('.jpg','Joint Photographic Experts Group JFIF format',2,5,'SISTEMA',(SELECT current date FROM sysibm.sysdummy1))
/



INSERT INTO KSK_KIOSKO.KSK_ARCHIVO(
CORRELATIVO_COLECCION, CORRELATIVO_PAIS,CORRELATIVO_ROL,NOMBRE, 
DESCRIPCION,TAMANHO, EXTENSION, NRO_ORDEN, DESCAGABLE,DESTACADO,
RUTA_IMGPREVIA,RUTA_ARCHIVO,
FECHA_INICIO,FECHA_CADUCIDAD,FECHA_SINCRONIZACION,
ELIMINADO,USUARIO_REGISTRA)
VALUES(
16,1,3,'Archivo 01',
'Archivo de prueba 0001 desc', '10.0', '.jpg', 1, 1, 1,
'https://IP:PORT/YanbalKiosko/documentos/jhskfs78296i.jpg', 'https://IP:PORT/YanbalKiosko/documentos/jhskfs78296.pdf', 
(SELECT current date FROM sysibm.sysdummy1),(SELECT current date FROM sysibm.sysdummy1),(SELECT current date FROM sysibm.sysdummy1),
0,'SISTEMA'
)
/

INSERT INTO KSK_KIOSKO.KSK_ARCHIVO(
CORRELATIVO_COLECCION, CORRELATIVO_PAIS,CORRELATIVO_ROL,NOMBRE, 
DESCRIPCION,TAMANHO, EXTENSION, NRO_ORDEN, DESCAGABLE,DESTACADO,
RUTA_IMGPREVIA,RUTA_ARCHIVO,
FECHA_INICIO,FECHA_CADUCIDAD,FECHA_SINCRONIZACION,
ELIMINADO,USUARIO_REGISTRA)
VALUES(
16,1,3,'Archivo 02',
'Archivo de prueba 0002 desc', '20.0', '.jpg', 1, 1, 1,
'https://IP:PORT/YanbalKiosko/documentos/FFFFFFFFFFF.jpg', 'https://IP:PORT/YanbalKiosko/documentos/jhskFFFFFFFFF6.pdf', 
(SELECT current date FROM sysibm.sysdummy1),(SELECT current date FROM sysibm.sysdummy1),(SELECT current date FROM sysibm.sysdummy1),
0,'SISTEMA'
)

COMMIT
/


INSERT INTO KSK_DISPOSITIVO_ACTIVO(
CORRELATIVO_PAIS,USUARIO,
DISPOSITIVO_SIS,
TOKEN)
VALUES(
1,'usuarioAutenticado',
'Android',
'143ACDBE456453'
)