ALTER TABLE KSK_KIOSKO.KSK_ARCHIVO
   DROP FOREIGN KEY FK_COLECCION_01
/

ALTER TABLE KSK_KIOSKO.KSK_ARCHIVO
   DROP FOREIGN KEY FK_PAIS_01
/

ALTER TABLE KSK_KIOSKO.KSK_ARCHIVO
   DROP FOREIGN KEY FK_ROL_00
/

ALTER TABLE KSK_KIOSKO.KSK_ARCHIVO_ROL
   DROP FOREIGN KEY FK_ARCHIVO_00
/

ALTER TABLE KSK_KIOSKO.KSK_ARCHIVO_ROL
   DROP FOREIGN KEY FK_ROL_01
/

ALTER TABLE KSK_KIOSKO.KSK_COLECCION
   DROP FOREIGN KEY FK_COLECCION_00
/

ALTER TABLE KSK_KIOSKO.KSK_COLECCION
   DROP FOREIGN KEY FK_PAIS_02
/

ALTER TABLE KSK_KIOSKO.KSK_COLECCION
   DROP FOREIGN KEY FK_ROL_02
/

ALTER TABLE KSK_KIOSKO.KSK_DISPOSITIVO_ACTIVO
   DROP FOREIGN KEY FK_PAIS_00
/

ALTER TABLE KSK_KIOSKO.KSK_SESION_WEB
   DROP FOREIGN KEY FK_PAIS_03
/

DROP TABLE KSK_KIOSKO.KSK_ARCHIVO
/

DROP TABLE KSK_KIOSKO.KSK_ARCHIVO_ROL
/

DROP TABLE KSK_KIOSKO.KSK_BITACORA
/

DROP TABLE KSK_KIOSKO.KSK_COLECCION
/

DROP TABLE KSK_KIOSKO.KSK_DISPOSITIVO_ACTIVO
/

DROP TABLE KSK_KIOSKO.KSK_FORMATO_ARCHIVO
/

DROP TABLE KSK_KIOSKO.KSK_KIOSKO_LOG
/

DROP TABLE KSK_KIOSKO.KSK_PAIS
/

DROP TABLE KSK_KIOSKO.KSK_PARAMETRO
/

DROP TABLE KSK_KIOSKO.KSK_PUSH_ENVIO
/

DROP TABLE KSK_KIOSKO.KSK_ROL
/

DROP TABLE KSK_KIOSKO.KSK_SESION_WEB
/

--==============================================================
-- USER: KSK_KIOSKO
--==============================================================
--==============================================================
-- TABLE: KSK_ARCHIVO
--==============================================================
CREATE TABLE KSK_KIOSKO.KSK_ARCHIVO
(
   CORRELATIVO_ARCHIVO   INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1,NOMAXVALUE,NOCYCLE,NOCACHE,ORDER),
   CORRELATIVO_COLECCION INTEGER,
   CORRELATIVO_PAIS     INTEGER,
   CORRELATIVO_ROL      INTEGER,
   NOMBRE               VARCHAR(50),
   DESCRIPCION          VARCHAR(200),
   TAMANHO              VARCHAR(10),
   EXTENSION            VARCHAR(5),
   NRO_ORDEN            SMALLINT,
   DESCARGABLE          SMALLINT,
   DESTACADO            SMALLINT,
   RUTA_IMGPREVIA       VARCHAR(200),
   RUTA_ARCHIVO         VARCHAR(200),
   FECHA_INICIO         TIMESTAMP,
   FECHA_CADUCIDAD      TIMESTAMP,
   FECHA_SINCRONIZACION TIMESTAMP,
   ELIMINADO            SMALLINT,
   USUARIO_REGISTRA     VARCHAR(50),
   FECHA_REGISTRA       TIMESTAMP,
   USUARIO_MODIFICACION VARCHAR(50),
   FECHA_MODIFICACION   TIMESTAMP,
   NOTIFICADO           SMALLINT,
   CONSTRAINT PK_ARCHIVO PRIMARY KEY (CORRELATIVO_ARCHIVO)
)
/

--==============================================================
-- TABLE: KSK_ARCHIVO_ROL
--==============================================================
CREATE TABLE KSK_KIOSKO.KSK_ARCHIVO_ROL
(
   CORRELATIVO_ARCHIVO_ROL  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1,NOMAXVALUE,NOCYCLE,NOCACHE,ORDER),
   CORRELATIVO_ARCHIVO  INTEGER,
   CORRELATIVO_ROL      INTEGER,
   USUARIO_REGISTRA     VARCHAR(50),
   FECHA_REGISTRA       TIMESTAMP,
   USUARIO_MODIFICACION VARCHAR(50),
   FECHA_MODIFICACION   TIMESTAMP,
   CONSTRAINT PK_ARCHIVO_ROL PRIMARY KEY (CORRELATIVO_ARCHIVO_ROL)
)
/

--==============================================================
-- TABLE: KSK_BITACORA
--==============================================================
CREATE TABLE KSK_KIOSKO.KSK_BITACORA
(
   CORRELATIVO_BITACORA  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1,NOMAXVALUE,NOCYCLE,NOCACHE,ORDER),
   DESCRIPCION          VARCHAR(150),
   ACCION               VARCHAR(150),
   NOMBRE_ARCHIVO       VARCHAR(150),
   TAMANHO_ARCHIVO      VARCHAR(150),
   TIPO_ARCHIVO         VARCHAR(150),
   TIPO_DESCARGA        VARCHAR(150),
   USUARIO              VARCHAR(150),
   PLATAFORMA           VARCHAR(150),
   DISPOSITIVO_IDENTIFICADOR VARCHAR(150),
   FECHA_BITACORA       TIMESTAMP,
   CONSTRAINT PK_BITACORA PRIMARY KEY (CORRELATIVO_BITACORA)
)
/

--==============================================================
-- TABLE: KSK_COLECCION
--==============================================================
CREATE TABLE KSK_KIOSKO.KSK_COLECCION
(
   CORRELATIVO_COLECCION  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1,NOMAXVALUE,NOCYCLE,NOCACHE,ORDER),
   CORRELATIVO_COLECCION_PADRE INTEGER,
   CORRELATIVO_PAIS     INTEGER,
   CORRELATIVO_ROL      INTEGER,
   NOMBRE               VARCHAR(50),
   NIVEL                SMALLINT,
   NRO_ORDEN            SMALLINT,
   DESCRIPCION          VARCHAR(100),
   COLOR                VARCHAR(20),
   FECHA_SINCRONIZACION TIMESTAMP,
   USUARIO_REGISTRA     VARCHAR(50),
   FECHA_REGISTRA       TIMESTAMP,
   USUARIO_MODIFICACION VARCHAR(50),
   FECHA_MODIFICACION   TIMESTAMP,
   ELIMINADO            SMALLINT,
   CONSTRAINT PK_COLECCION PRIMARY KEY (CORRELATIVO_COLECCION)
)
/

--==============================================================
-- TABLE: KSK_DISPOSITIVO_ACTIVO
--==============================================================
CREATE TABLE KSK_KIOSKO.KSK_DISPOSITIVO_ACTIVO
(
   CORRELATIVO_DISPOSITIVO_ACTIVO  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1,NOMAXVALUE,NOCYCLE,NOCACHE,ORDER),
   CORRELATIVO_PAIS     INTEGER,
   USUARIO              VARCHAR(50),
   CLAVE                VARCHAR(50),
   NOTIFICACION_IDENTIFICADOR VARCHAR(300),
   DISPOSITIVO_SIS      VARCHAR(300),
   DISPOSITIVO_IDENTIFICADOR VARCHAR(300),
   TOKEN                VARCHAR(300),
   FECHA_REGISTRO       TIMESTAMP,
   FECHA_ULTIMA_SINC    TIMESTAMP,
   CONSTRAINT PK_TOKEN PRIMARY KEY (CORRELATIVO_DISPOSITIVO_ACTIVO)
)
/

--==============================================================
-- TABLE: KSK_FORMATO_ARCHIVO
--==============================================================
CREATE TABLE KSK_KIOSKO.KSK_FORMATO_ARCHIVO
(
   CORRELATIVO_FORMATO_ARCHIVO  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1,NOMAXVALUE,NOCYCLE,NOCACHE,ORDER),
   EXTENSION            VARCHAR(5),
   DESCRIPCION          VARCHAR(100),
   DESCARGA             NUMERIC(9,2),
   CARGA                NUMERIC(9,2),
   USUARIO_REGISTRA     VARCHAR(50),
   FECHA_REGISTRA       TIMESTAMP,
   USUARIO_MODIFICACION VARCHAR(50),
   FECHA_MODIFICACION   TIMESTAMP,
   CONSTRAINT PK_FORMATO_ARCHIVO PRIMARY KEY (CORRELATIVO_FORMATO_ARCHIVO)
)
/

--==============================================================
-- TABLE: KSK_KIOSKO_LOG
--==============================================================
CREATE TABLE KSK_KIOSKO.KSK_KIOSKO_LOG
(
   CORRELATIVO_LOG       INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1,NOMAXVALUE,NOCYCLE,NOCACHE,ORDER),
   APLICACION           VARCHAR(200),
   DIRECCIONIP          VARCHAR(200),
   USUARIO              VARCHAR(200),
   NIVELERROR           VARCHAR(200),
   CLASE                VARCHAR(200),
   REFOBJPRINCIPAL      VARCHAR(200),
   MENSAJE              VARCHAR(200),
   EXCEPCION            VARCHAR(200),
   PILA                 VARCHAR(5000),
   CONSTRAINT PK_KIOSKO_LOG PRIMARY KEY (CORRELATIVO_LOG)
)
/

--==============================================================
-- TABLE: KSK_PAIS
--==============================================================
CREATE TABLE KSK_KIOSKO.KSK_PAIS
(
   CORRELATIVO_PAIS      INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1,NOMAXVALUE,NOCYCLE,NOCACHE,ORDER),
   NOMBRE               VARCHAR(50),
   CODIGO_PAIS          VARCHAR(10),
   CONSTRAINT PK_PAIS PRIMARY KEY (CORRELATIVO_PAIS)
)
/

--==============================================================
-- TABLE: KSK_PARAMETRO
--==============================================================
CREATE TABLE KSK_KIOSKO.KSK_PARAMETRO
(
   CORRELATIVO_PARAMETRO  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1,NOMAXVALUE,NOCYCLE,NOCACHE,ORDER),
   NOMBRE_PARAMETRO     VARCHAR(50) NOT NULL UNIQUE,
   VALOR_PARAMETRO      VARCHAR(50),
   CONSTRAINT PK_PARAMETRO PRIMARY KEY (CORRELATIVO_PARAMETRO)
)
/

--==============================================================
-- TABLE: KSK_PUSH_ENVIO
--==============================================================
CREATE TABLE KSK_KIOSKO.KSK_PUSH_ENVIO
(
   CORRELATIVO_PUSH_ENVIO  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1,NOMAXVALUE,NOCYCLE,NOCACHE,ORDER),
   MENSAJE              VARCHAR(200),
   FECHA_HORA_INICIO    TIMESTAMP,
   FECHA_HORA_FIN       TIMESTAMP,
   EXITOSOS             INTEGER,
   ERRORES              INTEGER,
   MOTIVO_ERROR         VARCHAR(200),
   PLATAFORMA           VARCHAR(200),
   PAIS                 VARCHAR(200),
   CONSTRAINT PK_PUSH_ENVIO PRIMARY KEY (CORRELATIVO_PUSH_ENVIO)
)
/

--==============================================================
-- TABLE: KSK_ROL
--==============================================================
CREATE TABLE KSK_KIOSKO.KSK_ROL
(
   CORRELATIVO_ROL       INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1,NOMAXVALUE,NOCYCLE,NOCACHE,ORDER),
   NOMBRE               VARCHAR(50),
   CODIGO_ROL           VARCHAR(10),
   CONSTRAINT PK_ROL PRIMARY KEY (CORRELATIVO_ROL)
)
/

--==============================================================
-- TABLE: KSK_SESION_WEB
--==============================================================
CREATE TABLE KSK_KIOSKO.KSK_SESION_WEB
(
   CORRELATIVO_SESION_WEB  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1,NOMAXVALUE,NOCYCLE,NOCACHE,ORDER),
   CORRELATIVO_PAIS     INTEGER,
   USUARIO              VARCHAR(50),
   CLAVE                VARCHAR(50),
   TOKEN                VARCHAR(100),
   FECHA_REGISTRO       TIMESTAMP,
   CONSTRAINT PK_TOKEN PRIMARY KEY (CORRELATIVO_SESION_WEB)
)
/

ALTER TABLE KSK_KIOSKO.KSK_ARCHIVO
   ADD CONSTRAINT FK_COLECCION_01 FOREIGN KEY (CORRELATIVO_COLECCION)
      REFERENCES KSK_KIOSKO.KSK_COLECCION (CORRELATIVO_COLECCION)
      ON DELETE RESTRICT ON UPDATE RESTRICT
/

ALTER TABLE KSK_KIOSKO.KSK_ARCHIVO
   ADD CONSTRAINT FK_PAIS_01 FOREIGN KEY (CORRELATIVO_PAIS)
      REFERENCES KSK_KIOSKO.KSK_PAIS (CORRELATIVO_PAIS)
      ON DELETE RESTRICT ON UPDATE RESTRICT
/

ALTER TABLE KSK_KIOSKO.KSK_ARCHIVO
   ADD CONSTRAINT FK_ROL_00 FOREIGN KEY (CORRELATIVO_ROL)
      REFERENCES KSK_KIOSKO.KSK_ROL (CORRELATIVO_ROL)
      ON DELETE RESTRICT ON UPDATE RESTRICT
/

ALTER TABLE KSK_KIOSKO.KSK_ARCHIVO_ROL
   ADD CONSTRAINT FK_ARCHIVO_00 FOREIGN KEY (CORRELATIVO_ARCHIVO)
      REFERENCES KSK_KIOSKO.KSK_ARCHIVO (CORRELATIVO_ARCHIVO)
      ON DELETE RESTRICT ON UPDATE RESTRICT
/

ALTER TABLE KSK_KIOSKO.KSK_ARCHIVO_ROL
   ADD CONSTRAINT FK_ROL_01 FOREIGN KEY (CORRELATIVO_ROL)
      REFERENCES KSK_KIOSKO.KSK_ROL (CORRELATIVO_ROL)
      ON DELETE RESTRICT ON UPDATE RESTRICT
/

ALTER TABLE KSK_KIOSKO.KSK_COLECCION
   ADD CONSTRAINT FK_COLECCION_00 FOREIGN KEY (CORRELATIVO_COLECCION_PADRE)
      REFERENCES KSK_KIOSKO.KSK_COLECCION (CORRELATIVO_COLECCION)
      ON DELETE RESTRICT ON UPDATE RESTRICT
/

ALTER TABLE KSK_KIOSKO.KSK_COLECCION
   ADD CONSTRAINT FK_PAIS_02 FOREIGN KEY (CORRELATIVO_PAIS)
      REFERENCES KSK_KIOSKO.KSK_PAIS (CORRELATIVO_PAIS)
      ON DELETE RESTRICT ON UPDATE RESTRICT
/

ALTER TABLE KSK_KIOSKO.KSK_COLECCION
   ADD CONSTRAINT FK_ROL_02 FOREIGN KEY (CORRELATIVO_ROL)
      REFERENCES KSK_KIOSKO.KSK_ROL (CORRELATIVO_ROL)
      ON DELETE RESTRICT ON UPDATE RESTRICT
/

ALTER TABLE KSK_KIOSKO.KSK_DISPOSITIVO_ACTIVO
   ADD CONSTRAINT FK_PAIS_00 FOREIGN KEY (CORRELATIVO_PAIS)
      REFERENCES KSK_KIOSKO.KSK_PAIS (CORRELATIVO_PAIS)
      ON DELETE RESTRICT ON UPDATE RESTRICT
/

ALTER TABLE KSK_KIOSKO.KSK_SESION_WEB
   ADD CONSTRAINT FK_PAIS_03 FOREIGN KEY (CORRELATIVO_PAIS)
      REFERENCES KSK_KIOSKO.KSK_PAIS (CORRELATIVO_PAIS)
      ON DELETE RESTRICT ON UPDATE RESTRICT
/