ALTER TABLE KSK_KIOSKO.KSK_FORMATO_ARCHIVO ALTER COLUMN DESCARGA SET DATA TYPE DECIMAL(5,2) 
ALTER COLUMN CARGA SET DATA TYPE DECIMAL(5,2);
CALL SYSPROC.ADMIN_CMD( 'REORG TABLE KSK_KIOSKO.KSK_FORMATO_ARCHIVO USE TEMPSPACE1' );

ALTER TABLE KSK_KIOSKO.KSK_PAIS ADD HABILITADO SMALLINT;
CALL SYSPROC.ADMIN_CMD( 'REORG TABLE KSK_KIOSKO.KSK_PAIS USE TEMPSPACE1' );

