SET SCHEMA KSK_KIOSKO;
/

INSERT INTO  KSK_KIOSKO.KSK_PARAMETRO(NOMBRE_PARAMETRO, VALOR_PARAMETRO)VALUES('FechaUltimaActualizacionPais','02/07/2015');
INSERT INTO  KSK_KIOSKO.KSK_PARAMETRO(NOMBRE_PARAMETRO, VALOR_PARAMETRO)VALUES('HorasExpiracionToken','24');

INSERT INTO KSK_KIOSKO.KSK_PAIS(NOMBRE,CODIGO_PAIS,HABILITADO) VALUES('PERU','PER',1);
INSERT INTO KSK_KIOSKO.KSK_PAIS(NOMBRE,CODIGO_PAIS,HABILITADO) VALUES('COLOMBIA','COL',1);
INSERT INTO KSK_KIOSKO.KSK_PAIS(NOMBRE,CODIGO_PAIS,HABILITADO) VALUES('BOLIVIA','BOL',1);
INSERT INTO KSK_KIOSKO.KSK_PAIS(NOMBRE,CODIGO_PAIS,HABILITADO) VALUES('ECUADOR','ECU',1);
INSERT INTO KSK_KIOSKO.KSK_PAIS(NOMBRE,CODIGO_PAIS,HABILITADO) VALUES('GUATEMALA','GTM',1);
INSERT INTO KSK_KIOSKO.KSK_PAIS(NOMBRE,CODIGO_PAIS,HABILITADO) VALUES('MEXICO','MEX',1);
INSERT INTO KSK_KIOSKO.KSK_PAIS(NOMBRE,CODIGO_PAIS,HABILITADO) VALUES('VENEZUELA','VEN',1);

INSERT INTO KSK_KIOSKO.KSK_ROL(NOMBRE,CODIGO_ROL,ROL_MOVIL) VALUES('Directora','2',1);
INSERT INTO KSK_KIOSKO.KSK_ROL(NOMBRE,CODIGO_ROL,ROL_MOVIL) VALUES('Consultora','4',1);
INSERT INTO KSK_KIOSKO.KSK_ROL(NOMBRE,CODIGO_ROL,ROL_MOVIL) VALUES('Estrella','1',1);
INSERT INTO KSK_KIOSKO.KSK_ROL(NOMBRE,CODIGO_ROL,ROL_MOVIL) VALUES('Staff','0',1);
INSERT INTO KSK_KIOSKO.KSK_ROL(NOMBRE,CODIGO_ROL,ROL_MOVIL) VALUES('Aspirante','3',1);
INSERT INTO KSK_KIOSKO.KSK_ROL(NOMBRE,CODIGO_ROL,ROL_MOVIL) VALUES('Admin CORP','2',0);
INSERT INTO KSK_KIOSKO.KSK_ROL(NOMBRE,CODIGO_ROL,ROL_MOVIL) VALUES('Admin UN','3',0);

INSERT INTO KSK_KIOSKO.KSK_FORMATO_ARCHIVO(CORRELATIVO_ROL, CORRELATIVO_PAIS,EXTENSION,DESCRIPCION,DESCARGA,CARGA,USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(6,1,'PDF','Portable Document Format',20,50,'SISTEMA',(SELECT current timestamp FROM sysibm.sysdummy1));

INSERT INTO KSK_KIOSKO.KSK_FORMATO_ARCHIVO(CORRELATIVO_ROL, CORRELATIVO_PAIS,EXTENSION,DESCRIPCION,DESCARGA,CARGA,USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(6,1,'MP4','MPEG-4 Video Stream',20,50,'SISTEMA',(SELECT current timestamp FROM sysibm.sysdummy1));

INSERT INTO KSK_KIOSKO.KSK_FORMATO_ARCHIVO(CORRELATIVO_ROL, CORRELATIVO_PAIS,EXTENSION,DESCRIPCION,DESCARGA,CARGA,USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(6,1,'MP3','MPEG Layer 3 Audio',10,15,'SISTEMA',(SELECT current timestamp FROM sysibm.sysdummy1));

INSERT INTO KSK_KIOSKO.KSK_FORMATO_ARCHIVO(CORRELATIVO_ROL, CORRELATIVO_PAIS,EXTENSION,DESCRIPCION,DESCARGA,CARGA,USUARIO_REGISTRA, FECHA_REGISTRA) 
VALUES(6,1,'JPG','Joint Photographic Experts Group JFIF format',20,50,'SISTEMA',(SELECT current timestamp FROM sysibm.sysdummy1));


COMMIT
/
/
