//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Reglas.java
//  @ Date : 29/04/2015
//  @ Author : 
//
//



package com.yanbal.lib.corp.reglas;


public interface Reglas {
}
