//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Untitled
// @ File Name : AudDatosDB.java
// @ Date : 29/04/2015
// @ Author :
//
//



package com.yanbal.lib.corp.auditoria;

import com.yanbal.lib.corp.bean.EventoAuditoriaDatos;

/**
 * Implementación de la auditoria de datos mediante base de datos
 * 
 * @author jcabrera
 * @author ovalencia
 * @version 1.0 Abril 2015
 */
public class AudDatosDB implements com.yanbal.lib.corp.interfaces.IAuditoriaDatos {
  /** Objeto de conexcion a la BD */
  public Object conexionDB;

  /**
   * Escribe una linea de log
   * 
   * @param linea bean que representa una linea de log
   */
  public void escribir(EventoAuditoriaDatos linea) {

  }


}
