//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Untitled
// @ File Name : ConfiguracionArchivo.java
// @ Date : 29/04/2015
// @ Author :
//
//



package com.yanbal.lib.corp.configuracion;

/**
 * Clase de implementación de lectura de configuraciones desde un archivo
 * 
 * @author jcabrera
 * @author ovalencia
 * @version 1.0 Abril 2015
 */

public class ConfiguracionArchivo extends com.yanbal.lib.corp.interfaces.IConfiguracion {



}
